- Sanjeevs_notes.md
- docker-compose.prod.yml
- docker-compose.yml
- mishmash/frontend/Dockerfile
This PR introduces a dual-environment Docker setup for development and production workflows.
- Uses Docker Compose Watch for hot reloading
- Mounts source code directories for live development
- Features:
- Frontend: React dev server on port 3000 with hot reload
- Backend: Django debug mode with auto-reload
- Source code mounted directly for instant updates
- Node modules in isolated volume
Usage:
```bash
docker compose watch
> finished docker setup for prod and dev setups

- docker-compose.yml
This PR adds a development setup using Docker Compose to enable live code changes for both the backend and frontend. The changes improve developer productivity by automatically reflecting updates in the running application without needing to rebuild the containers manually.
- Backend live code updates: The backend container is configured to restart or reload automatically when changes are made to the codebase.
- Frontend live code updates: The frontend container supports hot reloading to reflect UI changes instantly.
> added docker watch to backend

- .github/workflows/mainBranchDeploy.yml
looks like i need to merge to test the action
> GitHub actions

- .github/workflows/mainBranch_dev_server_emergency.yml
> add manual deploy

- .github/workflows/Dev Server Deploy Latest Main.yml
- .github/workflows/PROD server Deploy Latest.yml
- .github/workflows/PROD_server_emergency copy.yml
- .github/workflows/Testing Server Deploy Latest.yml
- .github/workflows/Testing_server_emergency.yml
- .github/workflows/dev_server_emergency.yml
> fix env url

- mishmash/Dockerfile.prod
- mishmash/frontend/.dockerignore
- mishmash/frontend/Dockerfile.prod
had to add back the production versions for the dockerfile for prod frontend and backend
> re add missing dockerfile.prod

- mishmash/api/views.py
- mishmash/frontend/src/components/ProgramForm.js
Made questions read-only, and removed them from the admin create/edit program form.
> Read only questions

- docker-compose.dev.yml
- docker-compose.yml
- mishmash/frontend/src/pages/ApplicationPage.js
- mishmash/frontend/src/utils/axios.js
- nginx/default.conf
This fixes only the local docker setup deployment. still working on the deployed api paths.
> Fix api path

- .github/workflows/Dev Server Deploy Latest Main.yml
- .github/workflows/PROD server Deploy Latest.yml
- .github/workflows/PROD_server_emergency copy.yml
- .github/workflows/Testing Server Deploy Latest.yml
- .github/workflows/Testing_server_emergency.yml
- .github/workflows/dev_server_emergency.yml
- docker-compose.dev.yml
- docker-compose.prod.yml
- docker-compose.test.yml
- mishmash/frontend/src/utils/axios.js
fixed the base url to use the env var and set proper env var.
had docker remove all containers on redeploy to prevent old react built code from being deployed.
*also deletes mysql db data
> Proper api path fix

- mishmash/frontend/src/components/AdminProgramsTable.js
- mishmash/frontend/src/components/ApplicantTable.js
- mishmash/frontend/src/components/ProgramCard.js
- mishmash/frontend/src/pages/ApplicationPage.js
- mishmash/frontend/src/pages/Dashboard.js
Fixed change password stuff
Fixed dashboard routes
Fixed application routes
Fixed admin view application routes
> Fixed some routing issues introduced in my last merge

- mishmash/api/management/commands/add_test_applications.py
- mishmash/api/management/commands/add_test_programs.py
- mishmash/api/management/commands/add_test_users.py
Cleaned up redundant object creation in test data. Also added -prod flag so users can be generated without creating a superuser. Admin password was made slightly more secure.
> Add test data cleanup

- .gitignore
- docker-compose.test.yml
these changes shouldnt hurt prod, just compose file stuff for test server  (removing prod data from test server) and .gitignore stuff
> update prod from main

- mishmash/api/admin.py
- mishmash/api/management/commands/test_api_endpoints.py
- mishmash/api/models.py
- mishmash/api/serializers.py
- mishmash/api/urls.py
- mishmash/api/views.py
- mishmash/frontend/src/components/AdminAppView.js
- mishmash/frontend/src/components/ApplicantTable.js
- mishmash/frontend/src/components/LoginModal.js
- mishmash/frontend/src/components/TopNavBar.js
- mishmash/frontend/src/context/AuthContext.js
- mishmash/frontend/src/pages/ApplicationPage.js
- mishmash/frontend/src/pages/Dashboard.js
- mishmash/frontend/src/pages/HomePage.js
SA-178 resolved 
Added confidential notes + tests;
Fixed user.user permanantly
> Confidential notes

- mishmash/api/views.py
- mishmash/frontend/src/components/AdminProgramsTable.js
resolved ampersand in program title bug
> Jason misc

- mishmash/api/views.py
- mishmash/frontend/src/components/ApplicantTable.js
- mishmash/frontend/src/components/DocumentStatusDisplay.js
- mishmash/frontend/src/components/EssentialDocumentFormSubmission.js
- mishmash/frontend/src/components/MyProgramsTable.js
- mishmash/frontend/src/components/PDFUploadForm.js
- mishmash/frontend/src/pages/ApplicationPage.js
SA-155
Refactored Documents and Application Page
> Mpt documents

- mishmash/frontend/src/components/SessionExpiredDialog.js
- mishmash/frontend/src/components/TopNavBar.js
- mishmash/frontend/src/context/AuthContext.js
- mishmash/frontend/src/utils/constants.js
- mishmash/mishmash/settings.py
> Session timeout new

- mishmash/mishmash/settings.py
> add page redirect

- mishmash/frontend/src/components/DeadlineIndicator.js
- mishmash/frontend/src/components/EssentialDocumentFormSubmission.js
- mishmash/frontend/src/components/MyProgramsTable.js
- mishmash/frontend/src/pages/ApplicationPage.js
- mishmash/frontend/src/utils/constants.js
Fixed application page to enforce different states same for documents
UI fixes for deadline indicator
Application form now shows all program info
> application states enforced and other ui fixes

- mishmash/api/views.py
- mishmash/frontend/src/components/AdminProgramsTable.js
- mishmash/frontend/src/components/DeadlineIndicator.js
- mishmash/frontend/src/components/DocumentStatusDisplay.js
- mishmash/frontend/src/components/EssentialDocumentFormSubmission.js
- mishmash/frontend/src/components/FacultyPicklist.js
- mishmash/frontend/src/components/LoginModal.js
- mishmash/frontend/src/components/MyProgramsTable.js
- mishmash/frontend/src/components/ProgramBrowser.js
- mishmash/frontend/src/pages/ApplicationPage.js
- mishmash/frontend/src/pages/Dashboard.js
A ton of fixes I dont feel like listing, check the commits
> Bug fixes rnb23

- mishmash/frontend/src/components/AdminProgramsTable.js
- mishmash/frontend/src/components/ApplicantCountsCell.js
- mishmash/frontend/src/components/ApplicantTable.js
- mishmash/frontend/src/components/ProgramForm.js
- mishmash/frontend/src/utils/constants.js
Fixed all the issues @alexiscruzdavid brought up in bugs
> New adminprograms table applicant counts

- mishmash/frontend/src/pages/HomePage.js
fixing the sso redirect on homepage
> Bug fixes 2

- mishmash/frontend/src/components/AdminAppView.js
- mishmash/frontend/src/components/ProgramForm.js
- mishmash/frontend/src/utils/constants.js
added spring fall summer dropdown
> fixed the dropdown issues

- mishmash/api/views.py
- mishmash/frontend/src/components/ProgramForm.js
added system admin faculty lead logic
> Admin faculty lead

- mishmash/api/views.py
- mishmash/frontend/src/components/AdminAppView.js
- mishmash/frontend/src/components/DocumentReview.js
- mishmash/frontend/src/pages/Dashboard.js
Reviewer access to documents revoked
announcements management only available to admins
> Evol3 bug fixes

- mishmash/api/models.py
- mishmash/api/serializers.py
- mishmash/api/urls.py
- mishmash/api/views.py
- mishmash/frontend/src/components/AdminSiteBranding.js
- mishmash/frontend/src/components/TopNavBar.js
- mishmash/frontend/src/pages/Dashboard.js
- mishmash/frontend/src/pages/HomePage.js
- nginx/default.conf
I will revert this if it doesnt work
> tentative white label implementation. I can't test locally for some reason media files don't serve locally

- .github/workflows/Dev Server Deploy Latest Main.yml
- .github/workflows/PROD server Deploy Latest.yml
- .github/workflows/PROD_server_emergency copy.yml
- .github/workflows/Testing Server Deploy Latest.yml
- .github/workflows/Testing_server_emergency.yml
- .github/workflows/dev_server_emergency.yml
changed the docker clear all volumes line in github actions to just sudo rm rf the files that docker is storing locally on the computer. this way doesnt remove all the volumes, just the static files.
> untested change on all uses

- mishmash/frontend/src/components/ElectronicAssumptionOfRiskForm.js
- mishmash/frontend/src/components/ElectronicCodeOfConductForm.js
- mishmash/frontend/src/components/ElectronicDocumentHub.js
- mishmash/frontend/src/components/ElectronicHousingQuestionnaireForm.js
- mishmash/frontend/src/components/ElectronicMedicalHistoryForm.js
fix viewing e forms and updating them
> fix e forms
